site_name: Some Specification
repo_url: https://github.com/christo-ph/mkdocs_build_plantuml
repo_name: "christo-ph/mkdocs_build_plantuml"

theme:
  name: material
  language: en
  icon:
    logo: material/folder-open 
  feature:
    tabs: false
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_javascript:
  - javascript/images_dark.js

nav:
  - Example Diagram: "index.md"
  - About:
      - "License": "about/license.md"
      - "Release Notes": "about/release-notes.md"

plugins:
  - search: {}
  - exclude:
      glob:
        - diagrams/include/C4/*
  - build_plantuml:
      render: "server"
      bin_path: "/usr/local/bin/plantuml"
      server: "http://www.plantuml.com/plantuml"
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"
      theme_enabled: true
      theme_folder: "include/themes"
      theme_light: "light.puml"
      theme_dark: "dark.puml"
  - glightbox: # enable lightbox for images
      effect: zoom
      background: var(--md-default-bg-color)
        